name: Plugin build with maven

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "25.0.3"
          distribution: "temurin"

      - name: Build with maven
        run: mvn package

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/*.jar"
          tag: "release"
